# Generated by Django 6.0.2 on 2026-03-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Styroform', max_length=120)),
                ('hero_title', models.CharField(default='Build, Share, Collect Effortlessly.', max_length=200)),
                ('hero_subtitle', models.CharField(default='Build fast forms and collect responses with Styroform.', max_length=300)),
                ('hero_cta_text', models.CharField(default='Explore Forms', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_app_content')],
            },
        ),
    ]
